QT += gui widgets
LIBS += -ld3d9


SOURCES += \
    $$PWD/alternativa/engine3d/containers/kdcontainer.cpp \
    $$PWD/alternativa/engine3d/containers/kdnode.cpp \
    $$PWD/alternativa/engine3d/containers/receiver.cpp \
    $$PWD/alternativa/engine3d/core/depthrenderer.cpp \
    $$PWD/alternativa/engine3d/core/depthrendererblurfragmentshaderhlsl.cpp \
    $$PWD/alternativa/engine3d/core/depthrendererblurvertexshaderhlsl.cpp \
    $$PWD/alternativa/engine3d/core/depthrendererdepthfragmentshaderhlsl.cpp \
    $$PWD/alternativa/engine3d/core/depthrendererdepthvertexshaderhlsl.cpp \
    $$PWD/alternativa/engine3d/core/depthrendererlightfragmentshaderhlsl.cpp \
    $$PWD/alternativa/engine3d/core/depthrendererlightvertexshaderhlsl.cpp \
    $$PWD/alternativa/engine3d/core/depthrendererssaofragmentshaderhlsl.cpp \
    $$PWD/alternativa/engine3d/core/depthrendererssaovertexshaderhlsl.cpp \
    $$PWD/alternativa/engine3d/core/light3d.cpp \
    $$PWD/alternativa/engine3d/core/shadow.cpp \
    $$PWD/alternativa/engine3d/core/shadowatlas.cpp \
    $$PWD/alternativa/engine3d/core/shadowatlasfragmentshaderhlsl.cpp \
    $$PWD/alternativa/engine3d/core/shadowatlasvertexshaderhlsl.cpp \
    $$PWD/alternativa/engine3d/core/shadowcasterfragmentshaderhlsl.cpp \
    $$PWD/alternativa/engine3d/core/shadowcastervertexshaderhlsl.cpp \
    $$PWD/alternativa/engine3d/core/shadowmap.cpp \
    $$PWD/alternativa/engine3d/core/shadowmapfragmentshaderhlsl.cpp \
    $$PWD/alternativa/engine3d/core/shadowmapvertexshaderhlsl.cpp \
    $$PWD/alternativa/engine3d/core/shadowreceiverfragmentshaderhlsl.cpp \
    $$PWD/alternativa/engine3d/core/shadowreceiververtexshaderhlsl.cpp \
    $$PWD/alternativa/engine3d/core/shadowvolumefragmentshaderhlsl.cpp \
    $$PWD/alternativa/engine3d/core/shadowvolumevertexshaderhlsl.cpp \
    $$PWD/alternativa/engine3d/lights/directionallight.cpp \
    $$PWD/alternativa/engine3d/lights/omnilight.cpp \
    $$PWD/alternativa/engine3d/lights/spotlight.cpp \
    $$PWD/alternativa/engine3d/lights/tubelight.cpp \
    $$PWD/alternativa/engine3d/materials/animatedpaintfragmentshaderhlsl.cpp \
    $$PWD/alternativa/engine3d/materials/materialentry.cpp \
    $$PWD/alternativa/engine3d/materials/materialfragmentshaderhlsl.cpp \
    $$PWD/alternativa/engine3d/materials/materialvertexshaderhlsl.cpp \
    $$PWD/alternativa/engine3d/materials/paintvertexshaderhlsl.cpp \
    $$PWD/alternativa/engine3d/materials/texturematerialfragmentshaderhlsl.cpp \
    $$PWD/alternativa/engine3d/materials/texturematerialvertexshaderhlsl.cpp \
    $$PWD/alternativa/engine3d/materials/textureresourcesregistry.cpp \
    $$PWD/alternativa/engine3d/materials/trackmaterialvertexshaderhlsl.cpp \
    $$PWD/alternativa/engine3d/materials/uvmatrixprovider.cpp \
    $$PWD/alternativa/engine3d/objects/animsprite.cpp \
    $$PWD/alternativa/engine3d/objects/decal.cpp \
    $$PWD/alternativa/engine3d/objects/occluder.cpp \
    $$PWD/alternativa/engine3d/objects/skybox.cpp \
    $$PWD/alternativa/engine3d/primitives/plane.cpp \
    $$PWD/alternativa/gfx/core/bitmaptextureresource.cpp \
    $$PWD/alternativa/gfx/core/compressedtextureresource.cpp \
    $$PWD/alternativa/gfx/core/device.cpp \
    $$PWD/alternativa/gfx/core/programresource.cpp \
    $$PWD/alternativa/gfx/core/rendertargettextureresource.cpp \
    $$PWD/alternativa/gfx/core/textureresource.cpp \
    $$PWD/alternativa/gfx/hlslasm/hlslasm.cpp \
    $$PWD/alternativa/gfx/shadersampler/shadersampler.cpp \
    $$PWD/alternativa/proplib/objects/propmesh.cpp \
    $$PWD/alternativa/proplib/objects/propobject.cpp \
    $$PWD/alternativa/proplib/objects/propsprite.cpp \
    $$PWD/alternativa/proplib/proplibrary.cpp \
    $$PWD/alternativa/proplib/proplibregistry.cpp \
    $$PWD/alternativa/proplib/types/propdata.cpp \
    $$PWD/alternativa/proplib/types/propgroup.cpp \
    $$PWD/alternativa/proplib/types/proplod.cpp \
    $$PWD/alternativa/proplib/types/propstate.cpp \
    $$PWD/alternativa/proplib/utils/texturebytedatamap.cpp \
    $$PWD/alternativa/resource/stubbitmapdata.cpp \
    $$PWD/alternativa/tanks/display/usertitle/defaultusertitlesrender.cpp \
    $$PWD/alternativa/tanks/display/usertitle/effectindicator.cpp \
    $$PWD/alternativa/tanks/display/usertitle/progressbarskin.cpp \
    $$PWD/alternativa/tanks/display/usertitle/usertitle.cpp \
    $$PWD/alternativa/tanks/display/usertitle/usertitleprogressbar.cpp \
    $$PWD/alternativa/tanks/engine3d/cachedentitystat.cpp \
    $$PWD/alternativa/tanks/engine3d/materialsequence.cpp \
    $$PWD/alternativa/tanks/engine3d/materialsequenceregistry.cpp \
    $$PWD/alternativa/tanks/engine3d/tankstexturematerial.cpp \
    $$PWD/alternativa/tanks/engine3d/texturematerialfactory.cpp \
    $$PWD/alternativa/tanks/engine3d/texturematerialregistry.cpp \
    $$PWD/alternativa/tanks/engine3d/uvframe.cpp \
    $$PWD/alternativa/tanks/gui/progressbar.cpp \
    $$PWD/alternativa/tanks/materials/animatedpaintmaterial.cpp \
    $$PWD/alternativa/tanks/materials/paintmaterial.cpp \
    $$PWD/alternativa/tanks/materials/trackmaterial.cpp \
    $$PWD/alternativa/tanks/models/battlefield/decals/decalfactory.cpp \
    $$PWD/alternativa/tanks/models/battlefield/decals/fadingdecalsrenderer.cpp \
    $$PWD/alternativa/tanks/models/battlefield/decals/queue.cpp \
    $$PWD/alternativa/tanks/models/battlefield/decals/queueitem.cpp \
    $$PWD/alternativa/tanks/models/battlefield/dust/dust.cpp \
    $$PWD/alternativa/tanks/models/battlefield/effects/damageeffect.cpp \
    $$PWD/alternativa/tanks/models/battlefield/effects/damageupeffect.cpp \
    $$PWD/alternativa/tanks/models/battlefield/effects/levelup/levelupeffect.cpp \
    $$PWD/alternativa/tanks/models/battlefield/effects/levelup/lightbeam.cpp \
    $$PWD/alternativa/tanks/models/battlefield/effects/levelup/lightbeameffect.cpp \
    $$PWD/alternativa/tanks/models/battlefield/effects/levelup/lightwaveeffect.cpp \
    $$PWD/alternativa/tanks/models/battlefield/effects/levelup/sparkeffect.cpp \
    $$PWD/alternativa/tanks/models/battlefield/gamemode/daygamemode.cpp \
    $$PWD/alternativa/tanks/models/battlefield/gamemode/defaultgamemodel.cpp \
    $$PWD/alternativa/tanks/models/battlefield/gamemode/foggamemode.cpp \
    $$PWD/alternativa/tanks/models/battlefield/gamemode/gamemodes.cpp \
    $$PWD/alternativa/tanks/models/battlefield/gamemode/halloweengamemode.cpp \
    $$PWD/alternativa/tanks/models/battlefield/gamemode/newyeargamemode.cpp \
    $$PWD/alternativa/tanks/models/battlefield/gamemode/nightgamemode.cpp \
    $$PWD/alternativa/tanks/models/battlefield/gamemode/spacegamemode.cpp \
    $$PWD/alternativa/tanks/models/battlefield/hidableobjects/hidableobject3dwrapper.cpp \
    $$PWD/alternativa/tanks/models/battlefield/skybox/object3drevolver.cpp \
    $$PWD/alternativa/tanks/models/dom/sfx/allbeamproperties.cpp \
    $$PWD/alternativa/tanks/models/dom/sfx/animatedbeam.cpp \
    $$PWD/alternativa/tanks/models/dom/sfx/beameffects.cpp \
    $$PWD/alternativa/tanks/models/dom/sfx/dominationbeameffect.cpp \
    $$PWD/alternativa/tanks/models/effectsvisualization/effectsvisualizationmodel.cpp \
    $$PWD/alternativa/tanks/models/sfx/animatedlighteffect.cpp \
    $$PWD/alternativa/tanks/models/sfx/collisionobject3dpositionprovider.cpp \
    $$PWD/alternativa/tanks/models/sfx/colortransform/colortransformentry.cpp \
    $$PWD/alternativa/tanks/models/sfx/flame/flamethrowergraphiceffect.cpp \
    $$PWD/alternativa/tanks/models/sfx/flame/flamethrowersfxdata.cpp \
    $$PWD/alternativa/tanks/models/sfx/flame/flamethrowersfxmodel.cpp \
    $$PWD/alternativa/tanks/models/sfx/healing/healingguncameraeffect.cpp \
    $$PWD/alternativa/tanks/models/sfx/healing/healinggungraphiceffect.cpp \
    $$PWD/alternativa/tanks/models/sfx/healing/healinggunsfx.cpp \
    $$PWD/alternativa/tanks/models/sfx/lightanimation.cpp \
    $$PWD/alternativa/tanks/models/sfx/lightdatamanager.cpp \
    $$PWD/alternativa/tanks/models/sfx/muzzlepositionprovider.cpp \
    $$PWD/alternativa/tanks/models/sfx/omnistreamlighteffect.cpp \
    $$PWD/alternativa/tanks/models/sfx/particle.cpp \
    $$PWD/alternativa/tanks/models/sfx/shoot/gun/gunshootsfxdata.cpp \
    $$PWD/alternativa/tanks/models/sfx/shoot/gun/smokysfxmodel.cpp \
    $$PWD/alternativa/tanks/models/sfx/shoot/plasma/plasmasfxdata.cpp \
    $$PWD/alternativa/tanks/models/sfx/shoot/railgun/beameffect.cpp \
    $$PWD/alternativa/tanks/models/sfx/shoot/railgun/chargeeffect.cpp \
    $$PWD/alternativa/tanks/models/sfx/shoot/railgun/railgunsfxmodel.cpp \
    $$PWD/alternativa/tanks/models/sfx/shoot/railgun/shottrail.cpp \
    $$PWD/alternativa/tanks/models/sfx/shoot/ricochet/ricochetsfxmodel.cpp \
    $$PWD/alternativa/tanks/models/sfx/shoot/shaft/trail1.cpp \
    $$PWD/alternativa/tanks/models/sfx/shoot/shaft/trail2.cpp \
    $$PWD/alternativa/tanks/models/sfx/shoot/shaft/traileffect1.cpp \
    $$PWD/alternativa/tanks/models/sfx/shoot/shaft/traileffect2.cpp \
    $$PWD/alternativa/tanks/models/sfx/shoot/thunder/thundersfxdata.cpp \
    $$PWD/alternativa/tanks/models/sfx/shoot/thunder/thundershoteffect.cpp \
    $$PWD/alternativa/tanks/models/sfx/shoot/thunder/trail.cpp \
    $$PWD/alternativa/tanks/models/sfx/streamlighteffect.cpp \
    $$PWD/alternativa/tanks/models/sfx/tubelighteffect.cpp \
    $$PWD/alternativa/tanks/models/tank/criticalhit/tankcriticalhitgraphiceffect.cpp \
    $$PWD/alternativa/tanks/models/tank/criticalhit/tankcriticalhitmodel.cpp \
    $$PWD/alternativa/tanks/models/tank/explosion/explosiondata.cpp \
    $$PWD/alternativa/tanks/models/tank/explosion/tankexplosionmodel.cpp \
    $$PWD/alternativa/tanks/models/weapon/freeze/sfx/animatedplane.cpp \
    $$PWD/alternativa/tanks/models/weapon/freeze/sfx/freezegraphiceffect.cpp \
	$$PWD/alternativa/tanks/models/weapon/freeze/sfx/freezesfxmodel.cpp \
    $$PWD/alternativa/tanks/models/weapon/shaft/sfx/shaftsfxmodel.cpp \
    $$PWD/alternativa/tanks/models/weapon/shaft/shaftindicator.cpp \
    $$PWD/alternativa/tanks/services/materialregistry/impl/materialregistry.cpp \
    $$PWD/alternativa/tanks/sfx/animatedplaneeffectold.cpp \
    $$PWD/alternativa/tanks/sfx/animatedspriteeffect.cpp \
    $$PWD/alternativa/tanks/sfx/animatedspriteeffectnew.cpp \
    $$PWD/alternativa/tanks/sfx/blinker.cpp \
    $$PWD/alternativa/tanks/sfx/limiteddistanceanimatedspriteeffect.cpp \
    $$PWD/alternativa/tanks/sfx/movingobject3dpositionprovider.cpp \
    $$PWD/alternativa/tanks/sfx/planemuzzleflasheffect.cpp \
    $$PWD/alternativa/tanks/sfx/scalingobject3dpositionprovider.cpp \
    $$PWD/alternativa/tanks/sfx/sfxutils.cpp \
    $$PWD/alternativa/tanks/sfx/simpleplane.cpp \
    $$PWD/alternativa/tanks/sfx/staticobject3dpositionprovider.cpp \
    $$PWD/alternativa/tanks/utils/graphicsutils.cpp \
    $$PWD/alternativa/tanks/vehicles/tanks/calculatetrackspeed.cpp \
    $$PWD/alternativa/tanks/vehicles/tanks/skintextureregistry.cpp \
    $$PWD/alternativa/tanks/vehicles/tanks/trackskin.cpp \
    $$PWD/alternativa/utils/bitmaputils.cpp \
    $$PWD/alternativa/utils/bytearraymap.cpp \
    $$PWD/alternativa/utils/texturebytedata.cpp \
    $$PWD/alternativa/utils/textureutils/textureconstructor.cpp \
    $$PWD/com/alternativaplatform/projects/tanks/client/warfare/models/colortransform/struct/colortransformstruct.cpp \
    $$PWD/controls/panel/indicators.cpp \
    $$PWD/controls/panel/mainpanelrank.cpp \
    $$PWD/controls/playerinfo.cpp \
    $$PWD/directxview.cpp \
    $$PWD/flash/display/bitmapdata.cpp \
    $$PWD/flash/display/imageitem.cpp \
    $$PWD/flash/display/imagenodes.cpp \
    $$PWD/flash/display/stage.cpp \
    $$PWD/flash/display/stage3d.cpp \
    $$PWD/flash/display3D/context3d.cpp \
    $$PWD/flash/display3D/directxdata.cpp \
    $$PWD/flash/display3D/indexbuffer3d.cpp \
    $$PWD/flash/display3D/program3d.cpp \
    $$PWD/flash/display3D/textures/texture.cpp \
    $$PWD/flash/display3D/textures/texturebase.cpp \
    $$PWD/flash/display3D/vertexbuffer3d.cpp \
    $$PWD/forms/mainpanel.cpp \
    $$PWD/graphics_debug.cpp \
	$$PWD/directxgraphics.cpp \
	$$PWD/resource/images/imageresource.cpp \
	$$PWD/resource/images/imageresourcelist.cpp \
	$$PWD/alternativa/tanks/config/proplibloadingtask.cpp \
	$$PWD/resource/images/objectbitmapdata.cpp \
	$$PWD/alternativa/tanks/config/proplibsloader.cpp \
	$$PWD/alternativa/utils/taraparser.cpp \
	$$PWD/resource/images/imageresourceloader.cpp \
	$$PWD/alternativa/tanks/models/dom/cp/controlpointsprite.cpp \
	$$PWD/alternativa/tanks/models/sfx/healing/healinggunsfxmodel.cpp \
	$$PWD/alternativa/tanks/models/sfx/shoot/plasma/plasmasfxmodel.cpp \
	$$PWD/alternativa/tanks/models/sfx/shoot/thunder/thundersfxmodel.cpp \
	$$PWD/server/models/inventory/serverinventorymodel.cpp \
	$$PWD/alternativa/tanks/models/weapon/ricochet/tailtrail.cpp \


HEADERS += \
    $$PWD/alternativa/engine3d/containers/kdcontainer.h \
    $$PWD/alternativa/engine3d/containers/kdnode.h \
    $$PWD/alternativa/engine3d/containers/receiver.h \
    $$PWD/alternativa/engine3d/core/Clipping.h \
    $$PWD/alternativa/engine3d/core/MipMapping.h \
    $$PWD/alternativa/engine3d/core/depthrenderer.h \
    $$PWD/alternativa/engine3d/core/depthrendererblurfragmentshaderhlsl.h \
    $$PWD/alternativa/engine3d/core/depthrendererblurvertexshaderhlsl.h \
    $$PWD/alternativa/engine3d/core/depthrendererdepthfragmentshaderhlsl.h \
    $$PWD/alternativa/engine3d/core/depthrendererdepthvertexshaderhlsl.h \
    $$PWD/alternativa/engine3d/core/depthrendererlightfragmentshaderhlsl.h \
    $$PWD/alternativa/engine3d/core/depthrendererlightvertexshaderhlsl.h \
    $$PWD/alternativa/engine3d/core/depthrendererssaofragmentshaderhlsl.h \
    $$PWD/alternativa/engine3d/core/depthrendererssaovertexshaderhlsl.h \
    $$PWD/alternativa/engine3d/core/light3d.h \
    $$PWD/alternativa/engine3d/core/shadow.h \
    $$PWD/alternativa/engine3d/core/shadowatlas.h \
    $$PWD/alternativa/engine3d/core/shadowatlasfragmentshaderhlsl.h \
    $$PWD/alternativa/engine3d/core/shadowatlasvertexshaderhlsl.h \
    $$PWD/alternativa/engine3d/core/shadowcasterfragmentshaderhlsl.h \
    $$PWD/alternativa/engine3d/core/shadowcastervertexshaderhlsl.h \
    $$PWD/alternativa/engine3d/core/shadowmap.h \
    $$PWD/alternativa/engine3d/core/shadowmapfragmentshaderhlsl.h \
    $$PWD/alternativa/engine3d/core/shadowmapvertexshaderhlsl.h \
    $$PWD/alternativa/engine3d/core/shadowreceiverfragmentshaderhlsl.h \
    $$PWD/alternativa/engine3d/core/shadowreceiververtexshaderhlsl.h \
    $$PWD/alternativa/engine3d/core/shadowvolumefragmentshaderhlsl.h \
    $$PWD/alternativa/engine3d/core/shadowvolumevertexshaderhlsl.h \
    $$PWD/alternativa/engine3d/lights/directionallight.h \
    $$PWD/alternativa/engine3d/lights/omnilight.h \
    $$PWD/alternativa/engine3d/lights/spotlight.h \
    $$PWD/alternativa/engine3d/lights/tubelight.h \
    $$PWD/alternativa/engine3d/materials/animatedpaintfragmentshader.h \
    $$PWD/alternativa/engine3d/materials/animatedpaintfragmentshaderhlsl.h \
    $$PWD/alternativa/engine3d/materials/materialentry.h \
    $$PWD/alternativa/engine3d/materials/materialfragmentshaderhlsl.h \
    $$PWD/alternativa/engine3d/materials/materialvertexshaderhlsl.h \
    $$PWD/alternativa/engine3d/materials/paintvertexshader.h \
    $$PWD/alternativa/engine3d/materials/paintvertexshaderhlsl.h \
    $$PWD/alternativa/engine3d/materials/sharedparamsbits.h \
    $$PWD/alternativa/engine3d/materials/texturematerialfragmentshader.h \
    $$PWD/alternativa/engine3d/materials/texturematerialfragmentshaderhlsl.h \
    $$PWD/alternativa/engine3d/materials/texturematerialvertexshader.h \
    $$PWD/alternativa/engine3d/materials/texturematerialvertexshaderhlsl.h \
    $$PWD/alternativa/engine3d/materials/textureresourcesregistry.h \
    $$PWD/alternativa/engine3d/materials/trackmaterialvertexshader.h \
    $$PWD/alternativa/engine3d/materials/trackmaterialvertexshaderhlsl.h \
    $$PWD/alternativa/engine3d/materials/uvmatrixprovider.h \
    $$PWD/alternativa/engine3d/objects/animsprite.h \
    $$PWD/alternativa/engine3d/objects/decal.h \
    $$PWD/alternativa/engine3d/objects/occluder.h \
    $$PWD/alternativa/engine3d/objects/skybox.h \
    $$PWD/alternativa/engine3d/primitives/plane.h \
    $$PWD/alternativa/gfx/core/bitmaptextureresource.h \
    $$PWD/alternativa/gfx/core/compressedtextureresource.h \
    $$PWD/alternativa/gfx/core/device.h \
    $$PWD/alternativa/gfx/core/programresource.h \
    $$PWD/alternativa/gfx/core/rendertargettextureresource.h \
    $$PWD/alternativa/gfx/core/textureresource.h \
    $$PWD/alternativa/gfx/hlslasm/hlslasm.h \
    $$PWD/alternativa/gfx/shadersampler/shadersampler.h \
    $$PWD/alternativa/proplib/objects/PropObjectType.h \
    $$PWD/alternativa/proplib/objects/propmesh.h \
    $$PWD/alternativa/proplib/objects/propobject.h \
    $$PWD/alternativa/proplib/objects/propsprite.h \
    $$PWD/alternativa/proplib/proplibrary.h \
    $$PWD/alternativa/proplib/proplibregistry.h \
    $$PWD/alternativa/proplib/types/propdata.h \
    $$PWD/alternativa/proplib/types/propgroup.h \
    $$PWD/alternativa/proplib/types/proplod.h \
    $$PWD/alternativa/proplib/types/propstate.h \
    $$PWD/alternativa/proplib/utils/texturebytedatamap.h \
    $$PWD/alternativa/resource/stubbitmapdata.h \
    $$PWD/alternativa/tanks/camera/ICameraStateModifier.h \
    $$PWD/alternativa/tanks/camera/IRender3D.h \
    $$PWD/alternativa/tanks/display/usertitle/UserTitlesRender.h \
    $$PWD/alternativa/tanks/display/usertitle/defaultusertitlesrender.h \
    $$PWD/alternativa/tanks/display/usertitle/effectindicator.h \
    $$PWD/alternativa/tanks/display/usertitle/progressbarskin.h \
    $$PWD/alternativa/tanks/display/usertitle/usertitle.h \
    $$PWD/alternativa/tanks/display/usertitle/usertitleprogressbar.h \
    $$PWD/alternativa/tanks/engine3d/IMaterialSequenceRegistry.h \
    $$PWD/alternativa/tanks/engine3d/ITextureMaterialRegistry.h \
    $$PWD/alternativa/tanks/engine3d/MaterialType.h \
    $$PWD/alternativa/tanks/engine3d/cachedentitystat.h \
    $$PWD/alternativa/tanks/engine3d/materialsequence.h \
    $$PWD/alternativa/tanks/engine3d/materialsequenceregistry.h \
    $$PWD/alternativa/tanks/engine3d/tankstexturematerial.h \
    $$PWD/alternativa/tanks/engine3d/textureanimation.h \
    $$PWD/alternativa/tanks/engine3d/texturematerialfactory.h \
    $$PWD/alternativa/tanks/engine3d/texturematerialregistry.h \
    $$PWD/alternativa/tanks/engine3d/uvframe.h \
    $$PWD/alternativa/tanks/gui/progressbar.h \
    $$PWD/alternativa/tanks/materials/animatedpaintmaterial.h \
    $$PWD/alternativa/tanks/materials/paintmaterial.h \
    $$PWD/alternativa/tanks/materials/trackmaterial.h \
    $$PWD/alternativa/tanks/models/battlefield/decals/RotationState.h \
    $$PWD/alternativa/tanks/models/battlefield/decals/decalentry.h \
    $$PWD/alternativa/tanks/models/battlefield/decals/decalfactory.h \
    $$PWD/alternativa/tanks/models/battlefield/decals/fadingdecalsrenderer.h \
    $$PWD/alternativa/tanks/models/battlefield/decals/queue.h \
    $$PWD/alternativa/tanks/models/battlefield/decals/queueitem.h \
    $$PWD/alternativa/tanks/models/battlefield/dust/dust.h \
    $$PWD/alternativa/tanks/models/battlefield/effects/damageeffect.h \
    $$PWD/alternativa/tanks/models/battlefield/effects/damageupeffect.h \
    $$PWD/alternativa/tanks/models/battlefield/effects/levelup/levelupeffect.h \
    $$PWD/alternativa/tanks/models/battlefield/effects/levelup/lightbeam.h \
    $$PWD/alternativa/tanks/models/battlefield/effects/levelup/lightbeameffect.h \
    $$PWD/alternativa/tanks/models/battlefield/effects/levelup/lightwaveeffect.h \
    $$PWD/alternativa/tanks/models/battlefield/effects/levelup/sparkeffect.h \
    $$PWD/alternativa/tanks/models/battlefield/gamemode/daygamemode.h \
    $$PWD/alternativa/tanks/models/battlefield/gamemode/defaultgamemodel.h \
    $$PWD/alternativa/tanks/models/battlefield/gamemode/foggamemode.h \
    $$PWD/alternativa/tanks/models/battlefield/gamemode/gamemodes.h \
    $$PWD/alternativa/tanks/models/battlefield/gamemode/halloweengamemode.h \
    $$PWD/alternativa/tanks/models/battlefield/gamemode/newyeargamemode.h \
    $$PWD/alternativa/tanks/models/battlefield/gamemode/nightgamemode.h \
    $$PWD/alternativa/tanks/models/battlefield/gamemode/spacegamemode.h \
    $$PWD/alternativa/tanks/models/battlefield/hidableobjects/hidableobject3dwrapper.h \
    $$PWD/alternativa/tanks/models/battlefield/skybox/object3drevolver.h \
    $$PWD/alternativa/tanks/models/dom/sfx/BeamProperties.h \
    $$PWD/alternativa/tanks/models/dom/sfx/allbeamproperties.h \
    $$PWD/alternativa/tanks/models/dom/sfx/animatedbeam.h \
    $$PWD/alternativa/tanks/models/dom/sfx/beameffects.h \
    $$PWD/alternativa/tanks/models/dom/sfx/dominationbeameffect.h \
    $$PWD/alternativa/tanks/models/effectsvisualization/clientbattleeffect.h \
    $$PWD/alternativa/tanks/models/effectsvisualization/effectsvisualizationmodel.h \
    $$PWD/alternativa/tanks/models/inventory/InventoryItemType.h \
    $$PWD/alternativa/tanks/models/sfx/animatedlighteffect.h \
    $$PWD/alternativa/tanks/models/sfx/collisionobject3dpositionprovider.h \
    $$PWD/alternativa/tanks/models/sfx/colortransform/colortransformentry.h \
    $$PWD/alternativa/tanks/models/sfx/flame/IFlamethrowerSFXModel.h \
    $$PWD/alternativa/tanks/models/sfx/flame/flamethrowergraphiceffect.h \
    $$PWD/alternativa/tanks/models/sfx/flame/flamethrowersfxdata.h \
    $$PWD/alternativa/tanks/models/sfx/flame/flamethrowersfxmodel.h \
    $$PWD/alternativa/tanks/models/sfx/healing/IHealingGunEffectListener.h \
    $$PWD/alternativa/tanks/models/sfx/healing/healingguncameraeffect.h \
    $$PWD/alternativa/tanks/models/sfx/healing/healinggungraphiceffect.h \
    $$PWD/alternativa/tanks/models/sfx/healing/healinggunsfx.h \
    $$PWD/alternativa/tanks/models/sfx/lightanimation.h \
    $$PWD/alternativa/tanks/models/sfx/lightdatamanager.h \
    $$PWD/alternativa/tanks/models/sfx/lightingeffectrecord.h \
    $$PWD/alternativa/tanks/models/sfx/muzzlepositionprovider.h \
    $$PWD/alternativa/tanks/models/sfx/omnistreamlighteffect.h \
    $$PWD/alternativa/tanks/models/sfx/particle.h \
    $$PWD/alternativa/tanks/models/sfx/shoot/gun/gunshootsfxdata.h \
    $$PWD/alternativa/tanks/models/sfx/shoot/gun/smokysfxmodel.h \
    $$PWD/alternativa/tanks/models/sfx/shoot/plasma/plasmasfxdata.h \
    $$PWD/alternativa/tanks/models/sfx/shoot/railgun/RailgunShootSFXData.h \
    $$PWD/alternativa/tanks/models/sfx/shoot/railgun/beameffect.h \
    $$PWD/alternativa/tanks/models/sfx/shoot/railgun/chargeeffect.h \
    $$PWD/alternativa/tanks/models/sfx/shoot/railgun/railgunsfxmodel.h \
    $$PWD/alternativa/tanks/models/sfx/shoot/railgun/shottrail.h \
    $$PWD/alternativa/tanks/models/sfx/shoot/ricochet/IRicochetSFXModel.h \
    $$PWD/alternativa/tanks/models/sfx/shoot/ricochet/RicochetSFXData.h \
    $$PWD/alternativa/tanks/models/sfx/shoot/ricochet/ricochetsfxmodel.h \
    $$PWD/alternativa/tanks/models/sfx/shoot/shaft/ShaftTrailEffect.h \
    $$PWD/alternativa/tanks/models/sfx/shoot/shaft/trail1.h \
    $$PWD/alternativa/tanks/models/sfx/shoot/shaft/trail2.h \
    $$PWD/alternativa/tanks/models/sfx/shoot/shaft/traileffect1.h \
    $$PWD/alternativa/tanks/models/sfx/shoot/shaft/traileffect2.h \
    $$PWD/alternativa/tanks/models/sfx/shoot/thunder/thundersfxdata.h \
    $$PWD/alternativa/tanks/models/sfx/shoot/thunder/thundershoteffect.h \
    $$PWD/alternativa/tanks/models/sfx/shoot/thunder/trail.h \
    $$PWD/alternativa/tanks/models/sfx/streamlighteffect.h \
    $$PWD/alternativa/tanks/models/sfx/tubelighteffect.h \
    $$PWD/alternativa/tanks/models/tank/criticalhit/tankcriticalhitgraphiceffect.h \
    $$PWD/alternativa/tanks/models/tank/criticalhit/tankcriticalhitmodel.h \
    $$PWD/alternativa/tanks/models/tank/explosion/explosiondata.h \
    $$PWD/alternativa/tanks/models/tank/explosion/tankexplosionmodel.h \
    $$PWD/alternativa/tanks/models/weapon/flamethrower/IFlamethrower.h \
    $$PWD/alternativa/tanks/models/weapon/freeze/sfx/animatedplane.h \
    $$PWD/alternativa/tanks/models/weapon/freeze/sfx/freezegraphiceffect.h \
	$$PWD/alternativa/tanks/models/weapon/freeze/sfx/freezesfxmodel.h \
    $$PWD/alternativa/tanks/models/weapon/freeze/sfx/IFreezeSFXModel.h \
    $$PWD/alternativa/tanks/models/weapon/freeze/sfx/freezesfxdata.h \
    $$PWD/alternativa/tanks/models/weapon/shaft/sfx/ShaftSFXData.h \
    $$PWD/alternativa/tanks/models/weapon/shaft/sfx/shaftsfxmodel.h \
    $$PWD/alternativa/tanks/models/weapon/shaft/shaftindicator.h \
    $$PWD/alternativa/tanks/services/materialregistry/IMaterialRegistry.h \
    $$PWD/alternativa/tanks/services/materialregistry/impl/materialregistry.h \
    $$PWD/alternativa/tanks/sfx/ISound3DEffect.h \
    $$PWD/alternativa/tanks/sfx/Object3DPositionProvider.h \
    $$PWD/alternativa/tanks/sfx/animatedplaneeffectold.h \
    $$PWD/alternativa/tanks/sfx/animatedspriteeffect.h \
    $$PWD/alternativa/tanks/sfx/animatedspriteeffectnew.h \
    $$PWD/alternativa/tanks/sfx/blinker.h \
    $$PWD/alternativa/tanks/sfx/limiteddistanceanimatedspriteeffect.h \
    $$PWD/alternativa/tanks/sfx/movingobject3dpositionprovider.h \
    $$PWD/alternativa/tanks/sfx/planemuzzleflasheffect.h \
    $$PWD/alternativa/tanks/sfx/scalingobject3dpositionprovider.h \
    $$PWD/alternativa/tanks/sfx/sfxutils.h \
    $$PWD/alternativa/tanks/sfx/simpleplane.h \
    $$PWD/alternativa/tanks/sfx/staticobject3dpositionprovider.h \
    $$PWD/alternativa/tanks/utils/graphicsutils.h \
    $$PWD/alternativa/tanks/vehicles/tanks/ISkinTextureRegistry.h \
    $$PWD/alternativa/tanks/vehicles/tanks/calculatetrackspeed.h \
    $$PWD/alternativa/tanks/vehicles/tanks/skintextureregistry.h \
    $$PWD/alternativa/tanks/vehicles/tanks/trackskin.h \
    $$PWD/alternativa/utils/bitmaputils.h \
    $$PWD/alternativa/utils/bytearraymap.h \
    $$PWD/alternativa/utils/texturebytedata.h \
    $$PWD/alternativa/utils/textureutils/textureconstructor.h \
    $$PWD/com/alternativaplatform/projects/tanks/client/warfare/models/colortransform/struct/colortransformstruct.h \
    $$PWD/controls/panel/indicators.h \
    $$PWD/controls/panel/mainpanelrank.h \
    $$PWD/controls/playerinfo.h \
    $$PWD/directxview.h \
    $$PWD/flash/display/IBitmapDrawable.h \
    $$PWD/flash/display/bitmapdata.h \
    $$PWD/flash/display/imageitem.h \
    $$PWD/flash/display/imagenodes.h \
    $$PWD/flash/display/stage.h \
    $$PWD/flash/display/stage3d.h \
    $$PWD/flash/display3D/Context3DBlendFactor.h \
    $$PWD/flash/display3D/Context3DClearMask.h \
    $$PWD/flash/display3D/Context3DCompareMode.h \
    $$PWD/flash/display3D/Context3DMipFilter.h \
    $$PWD/flash/display3D/Context3DProfile.h \
    $$PWD/flash/display3D/Context3DRenderMode.h \
    $$PWD/flash/display3D/Context3DStencilAction.h \
    $$PWD/flash/display3D/Context3DTextureFilter.h \
    $$PWD/flash/display3D/Context3DTextureFormat.h \
    $$PWD/flash/display3D/Context3DTriangleFace.h \
    $$PWD/flash/display3D/Context3DVertexBufferFormat.h \
    $$PWD/flash/display3D/Context3DWrapMode.h \
    $$PWD/flash/display3D/Context3dProgramType.h \
    $$PWD/flash/display3D/context3d.h \
    $$PWD/flash/display3D/directxdata.h \
    $$PWD/flash/display3D/indexbuffer3d.h \
    $$PWD/flash/display3D/program3d.h \
    $$PWD/flash/display3D/textures/texture.h \
    $$PWD/flash/display3D/textures/texturebase.h \
    $$PWD/flash/display3D/vertexbuffer3d.h \
    $$PWD/forms/mainpanel.h \
    $$PWD/graphics_debug.h \
	$$PWD/directxgraphics.h \
    $$PWD/projects/tanks/client/battlefield/gui/models/effectsvisualization/battleeffect.h \
	$$PWD/resource/ImageType.h \
	$$PWD/resource/images/MultiframeResourceData.h \
	$$PWD/resource/images/imageresource.h \
	$$PWD/resource/images/imageresourcelist.h \
	$$PWD/resource/images/objectbitmapdata.h \
	$$PWD/alternativa/tanks/config/proplibloadingtask.h \
	$$PWD/alternativa/tanks/config/proplibsloader.h \
	$$PWD/alternativa/utils/taraparser.h \
	$$PWD//resource/images/imageresourceloader.h \
	$$PWD/server/models/inventory/ServerInventoryData.h \
	$$PWD/alternativa/tanks/models/dom/cp/controlpointsprite.h \
	$$PWD/alternativa/tanks/models/sfx/healing/healinggunsfxmodel.h \
	$$PWD/alternativa/tanks/models/sfx/shoot/plasma/plasmasfxmodel.h \
	$$PWD/alternativa/tanks/models/sfx/shoot/thunder/thundersfxmodel.h \
	$$PWD/alternativa/tanks/models/sfx/shoot/thunder/IThunderSFXModel.h \
	$$PWD/server/models/inventory/serverinventorymodel.h \
	$$PWD/alternativa/tanks/models/weapon/ricochet/tailtrail.h \

