QT += core network xml

VERSION = 1.8


DESTDIR = build
OBJECTS_DIR = objects
MOC_DIR = moc
UI_DIR = ui
RCC_DIR = res

CONFIG += c++11

QMAKE_CXXFLAGS += -mfpmath=sse -msse2
QMAKE_CFLAGS += -Wl,--stack=67108864

# You can make your code fail to compile if it uses deprecated APIs.
# In order to do so, uncomment the following line.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Default rules for deployment.
qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target



INCLUDEPATH += $$PWD

SOURCES += \
    $$PWD/_global.cpp \
    $$PWD/alternativa/engine3d/core/face.cpp \
    $$PWD/alternativa/engine3d/core/object3d.cpp \
    $$PWD/alternativa/engine3d/core/vertex.cpp \
    $$PWD/alternativa/engine3d/core/view.cpp \
    $$PWD/alternativa/engine3d/core/wrapper.cpp \
    $$PWD/alternativa/engine3d/loaders/parser3ds.cpp \
    $$PWD/alternativa/engine3d/materials/fillmaterial.cpp \
    $$PWD/alternativa/engine3d/materials/material.cpp \
    $$PWD/alternativa/engine3d/objects/mesh.cpp \
    $$PWD/alternativa/gfx/core/resource.cpp \
    $$PWD/alternativa/init/battlefieldsharedactivator.cpp \
    $$PWD/alternativa/init/garagemodelactivator.cpp \
    $$PWD/alternativa/init/osgi.cpp \
    $$PWD/alternativa/math/matrix3.cpp \
    $$PWD/alternativa/math/matrix4.cpp \
    $$PWD/alternativa/math/quaternion.cpp \
    $$PWD/alternativa/math/vector3.cpp \
    $$PWD/alternativa/object/clientobject.cpp \
    $$PWD/alternativa/object/clientobjectbonus.cpp \
    $$PWD/alternativa/object/clientobjectctf.cpp \
    $$PWD/alternativa/object/clientobjecthull.cpp \
    $$PWD/alternativa/object/clientobjectuser.cpp \
    $$PWD/alternativa/object/clientobjectweapon.cpp \
    $$PWD/alternativa/object/clientobjectweaponflamethrower.cpp \
    $$PWD/alternativa/object/clientobjectweaponfrezee.cpp \
    $$PWD/alternativa/object/clientobjectweaponisida.cpp \
    $$PWD/alternativa/object/clientobjectweaponrailgun.cpp \
    $$PWD/alternativa/object/clientobjectweaponricochet.cpp \
    $$PWD/alternativa/object/clientobjectweaponshaft.cpp \
    $$PWD/alternativa/object/clientobjectweaponsmoky.cpp \
    $$PWD/alternativa/object/clientobjectweaponterminator.cpp \
    $$PWD/alternativa/object/clientobjectweaponthunder.cpp \
    $$PWD/alternativa/object/clientobjectweapontwins.cpp \
    $$PWD/alternativa/physics/body.cpp \
    $$PWD/alternativa/physics/bodylist.cpp \
    $$PWD/alternativa/physics/bodylistitem.cpp \
    $$PWD/alternativa/physics/bodymaterial.cpp \
    $$PWD/alternativa/physics/bodystate.cpp \
    $$PWD/alternativa/physics/collision/colliders/boxboxcollider.cpp \
    $$PWD/alternativa/physics/collision/colliders/boxcollider.cpp \
    $$PWD/alternativa/physics/collision/colliders/boxrectcollider.cpp \
    $$PWD/alternativa/physics/collision/colliders/boxspherecollider.cpp \
    $$PWD/alternativa/physics/collision/colliders/boxtrianglecollider.cpp \
    $$PWD/alternativa/physics/collision/collisionkdnode.cpp \
    $$PWD/alternativa/physics/collision/collisionkdtree.cpp \
    $$PWD/alternativa/physics/collision/collisionkdtree2d.cpp \
	$$PWD/alternativa/physics/collision/collisionprimitive.cpp \
    $$PWD/alternativa/physics/collision/colliders/spherespherecollider.cpp \
    $$PWD/alternativa/physics/collision/kdtreecollisiondetector.cpp \
    $$PWD/alternativa/physics/collision/primitives/collisionbox.cpp \
    $$PWD/alternativa/physics/collision/primitives/collisionrect.cpp \
    $$PWD/alternativa/physics/collision/primitives/collisionsphere.cpp \
    $$PWD/alternativa/physics/collision/primitives/collisiontriangle.cpp \
    $$PWD/alternativa/physics/collision/types/boundbox.cpp \
    $$PWD/alternativa/physics/collision/types/rayintersection.cpp \
    $$PWD/alternativa/physics/collisionprimitivelist.cpp \
    $$PWD/alternativa/physics/collisionprimitivelistitem.cpp \
    $$PWD/alternativa/physics/constraints/constraint.cpp \
    $$PWD/alternativa/physics/constraints/maxdistanceconstraint.cpp \
    $$PWD/alternativa/physics/contact.cpp \
    $$PWD/alternativa/physics/contactpoint.cpp \
    $$PWD/alternativa/physics/physicsscene.cpp \
    $$PWD/alternativa/physics/physicsutils.cpp \
    $$PWD/alternativa/physics/rigid/body3d.cpp \
    $$PWD/alternativa/physics/rigid/skinnedbody3d.cpp \
    $$PWD/alternativa/tanks/battle/triggers/deferredtriggeraddition.cpp \
    $$PWD/alternativa/tanks/battle/triggers/deferredtriggerdeletion.cpp \
    $$PWD/alternativa/tanks/battle/triggers/triggers.cpp \
    $$PWD/alternativa/tanks/camera/anglevalues.cpp \
    $$PWD/alternativa/tanks/camera/cameracontrollerbase.cpp \
    $$PWD/alternativa/tanks/camera/camerafovcalculator.cpp \
    $$PWD/alternativa/tanks/camera/flycameracontroller.cpp \
    $$PWD/alternativa/tanks/camera/followcameracontroller.cpp \
    $$PWD/alternativa/tanks/camera/gamecamera.cpp \
    $$PWD/alternativa/tanks/config/config.cpp \
    $$PWD/alternativa/tanks/config/configxmlloader.cpp \
    $$PWD/alternativa/tanks/config/loaders/maploader.cpp \
    $$PWD/alternativa/tanks/config/resourceloader.cpp \
    $$PWD/alternativa/tanks/config/tanksmap.cpp \
    $$PWD/alternativa/tanks/gui/garagewindow.cpp \
    $$PWD/alternativa/tanks/gui/newyear/toylight.cpp \
    $$PWD/alternativa/tanks/model/battleselectmodel.cpp \
    $$PWD/alternativa/tanks/model/garagemodel.cpp \
    $$PWD/alternativa/tanks/model/itemparams.cpp \
    $$PWD/alternativa/tanks/model/panel/panelmodel.cpp \
    $$PWD/alternativa/tanks/model/tankpreview.cpp \
    $$PWD/alternativa/tanks/model/usermodel.cpp \
    $$PWD/alternativa/tanks/models/battlefield/ambientshadows.cpp \
	$$PWD/alternativa/tanks/models/battlefield/battlefieldmodel.cpp \
    $$PWD/alternativa/tanks/models/battlefield/battleview3d.cpp \
    $$PWD/alternativa/tanks/models/battlefield/hidableobjects/hidablegraphicobjects.cpp \
    $$PWD/alternativa/tanks/models/battlefield/logic/battlelogicunits.cpp \
    $$PWD/alternativa/tanks/models/battlefield/logic/updaters/localhulltransformupdater.cpp \
    $$PWD/alternativa/tanks/models/battlefield/logic/updaters/remotehulltransformupdater.cpp \
    $$PWD/alternativa/tanks/models/battlefield/mine/battleminesmodel.cpp \
    $$PWD/alternativa/tanks/models/battlefield/mine/proximitymine.cpp \
    $$PWD/alternativa/tanks/models/battlefield/mine/usermineslist.cpp \
    $$PWD/alternativa/tanks/models/battlefield/object3dnames.cpp \
    $$PWD/alternativa/tanks/models/battlefield/objects2tank.cpp \
    $$PWD/alternativa/tanks/models/battlefield/scene3dcontainer/object3dcontainerproxy.cpp \
    $$PWD/alternativa/tanks/models/ctf/ctfflag.cpp \
    $$PWD/alternativa/tanks/models/ctf/ctfflagstate.cpp \
    $$PWD/alternativa/tanks/models/ctf/ctfmodel.cpp \
    $$PWD/alternativa/tanks/models/ctf/flagdata.cpp \
    $$PWD/alternativa/tanks/models/ctf/initparams.cpp \
    $$PWD/alternativa/tanks/models/dom/cp/controlpointmarkers.cpp \
    $$PWD/alternativa/tanks/models/dom/dommodel.cpp \
    $$PWD/alternativa/tanks/models/dom/dompoint.cpp \
    $$PWD/alternativa/tanks/models/dom/dompointid.cpp \
    $$PWD/alternativa/tanks/models/effects/common/bonuscommon/battlebonusstate.cpp \
    $$PWD/alternativa/tanks/models/effects/common/bonuscommon/bonuscommonmodel.cpp \
    $$PWD/alternativa/tanks/models/effects/common/bonuscommon/bonusconst.cpp \
    $$PWD/alternativa/tanks/models/sfx/spriteshoteffect.cpp \
    $$PWD/alternativa/tanks/models/tank/tankdata.cpp \
    $$PWD/alternativa/tanks/models/tank/tankeventdispatcher.cpp \
    $$PWD/alternativa/tanks/models/tank/tankmodel.cpp \
    $$PWD/alternativa/tanks/models/tank/turret/default/defaultturretcontroller.cpp \
    $$PWD/alternativa/tanks/models/tank/turret/shaft/shaftturretcontroller.cpp \
    $$PWD/alternativa/tanks/models/weapon/common/weaponcommondata.cpp \
    $$PWD/alternativa/tanks/models/weapon/common/weaponcommonmodel.cpp \
	$$PWD/alternativa/tanks/models/weapon/flamethrower/flamethrowermodel.cpp \
    $$PWD/alternativa/tanks/models/weapon/flamethrower/flamethrowertargetvalidator.cpp \
    $$PWD/alternativa/tanks/models/weapon/freeze/freezemodel.cpp \
    $$PWD/alternativa/tanks/models/weapon/gun/smokymodel.cpp \
    $$PWD/alternativa/tanks/models/weapon/healing/healinggunmodel.cpp \
    $$PWD/alternativa/tanks/models/weapon/healing/healinggunshaft.cpp \
    $$PWD/alternativa/tanks/models/weapon/healing/healingguntargetsystem.cpp \
    $$PWD/alternativa/tanks/models/weapon/plasma/plasmamodel.cpp \
    $$PWD/alternativa/tanks/models/weapon/plasma/plasmashot.cpp \
    $$PWD/alternativa/tanks/models/weapon/railgun/railgunmodel.cpp \
    $$PWD/alternativa/tanks/models/weapon/railgun/railguntargetsystem.cpp \
    $$PWD/alternativa/tanks/models/weapon/ricochet/ricochetmodel.cpp \
    $$PWD/alternativa/tanks/models/weapon/ricochet/ricochetshot.cpp \
    $$PWD/alternativa/tanks/models/weapon/ricochet/ricochettargetsystem.cpp \
    $$PWD/alternativa/tanks/models/weapon/shaft/aim.cpp \
    $$PWD/alternativa/tanks/models/weapon/shaft/aimedshotresult.cpp \
    $$PWD/alternativa/tanks/models/weapon/shaft/cameracontrollers/targetingcameracontroller.cpp \
    $$PWD/alternativa/tanks/models/weapon/shaft/modes/targetingcontroller.cpp \
    $$PWD/alternativa/tanks/models/weapon/shaft/quickshot/shafttargetsystem.cpp \
    $$PWD/alternativa/tanks/models/weapon/shaft/setcontrollerfortemporaryitems.cpp \
    $$PWD/alternativa/tanks/models/weapon/shaft/shaftdeactivationtask.cpp \
    $$PWD/alternativa/tanks/models/weapon/shaft/shaftmodel.cpp \
    $$PWD/alternativa/tanks/models/weapon/shared/commontargetevaluator.cpp \
    $$PWD/alternativa/tanks/models/weapon/shared/commontargetsystem.cpp \
    $$PWD/alternativa/tanks/models/weapon/shared/commontargetsystembot.cpp \
    $$PWD/alternativa/tanks/models/weapon/shared/conicareatargetsystem.cpp \
    $$PWD/alternativa/tanks/models/weapon/shared/conicareatargetsystembot.cpp \
    $$PWD/alternativa/tanks/models/weapon/terminator/terminatormodel.cpp \
    $$PWD/alternativa/tanks/models/weapon/terminator/terminatortargetsystem.cpp \
    $$PWD/alternativa/tanks/models/weapon/thunder/thunderdata.cpp \
    $$PWD/alternativa/tanks/models/weapon/thunder/thundermodel.cpp \
    $$PWD/alternativa/tanks/models/weapon/weakening/weaponweakeningmodel.cpp \
    $$PWD/alternativa/tanks/models/weapon/weaponmodelempty.cpp \
    $$PWD/alternativa/tanks/models/weapon/weaponutils.cpp \
    $$PWD/alternativa/tanks/physics/tankscollisiondetector.cpp \
    $$PWD/alternativa/tanks/services/objectpool/objectpoolservice.cpp \
    $$PWD/alternativa/tanks/utils/mathutils.cpp \
    $$PWD/alternativa/tanks/utils/objectpool/objectpool.cpp \
    $$PWD/alternativa/tanks/utils/objectpool/pooledobject.cpp \
    $$PWD/alternativa/tanks/vehicles/tanks/raypredicate.cpp \
    $$PWD/alternativa/tanks/vehicles/tanks/suspensionray.cpp \
    $$PWD/alternativa/tanks/vehicles/tanks/tank.cpp \
    $$PWD/alternativa/tanks/vehicles/tanks/tankskin.cpp \
    $$PWD/alternativa/tanks/vehicles/tanks/tankskinhull.cpp \
    $$PWD/alternativa/tanks/vehicles/tanks/tankskinpart.cpp \
    $$PWD/alternativa/tanks/vehicles/tanks/tankskinturret.cpp \
    $$PWD/alternativa/tanks/vehicles/tanks/track.cpp \
    $$PWD/alternativa/tanks/vehicles/tanks/valuesmoother.cpp \
    $$PWD/alternativa/types/long.cpp \
	$$PWD/com/alternativaplatform/projects/tanks/client/commons/types/deathreason.cpp \
    $$PWD/battlechatmessage.cpp \
    $$PWD/battlecontroller.cpp \
    $$PWD/com/alternativaplatform/projects/tanks/client/commons/models/itemtype/itemtypeenumfromint.cpp \
    $$PWD/com/alternativaplatform/projects/tanks/client/commons/types/itempropertyfromstring.cpp \
    $$PWD/com/alternativaplatform/projects/tanks/client/warfare/models/tankparts/weapon/healing/IsisActionType.cpp \
    $$PWD/double_to_string.cpp \
    $$PWD/enterbattle.cpp \
    $$PWD/file.cpp \
    $$PWD/flash/geom/colortransform.cpp \
    $$PWD/flash/geom/matrix.cpp \
    $$PWD/flash/geom/matrix3d.cpp \
    $$PWD/flash/utils/gettimer.cpp \
    $$PWD/forms/garage/partslist.cpp \
    $$PWD/gametime.cpp \
    $$PWD/get_dir.cpp \
    $$PWD/hash.cpp \
    $$PWD/keys.cpp \
    $$PWD/listvector3.cpp \
    $$PWD/load_config.cpp \
    $$PWD/lobby.cpp \
    $$PWD/main.cpp \
    $$PWD/mymath.cpp \
    $$PWD/pro/battlemode.cpp \
    $$PWD/projects/tanks/client/battleselect/types/mapclient.cpp \
    $$PWD/projects/tanks/client/battleservice/model/battletype.cpp \
    $$PWD/projects/tanks/client/battleservice/model/team/BattleTeamType.cpp \
	$$PWD/networking/network.cpp \
	$$PWD/networking/networkbytes.cpp \
	$$PWD/networking/networkservice.cpp \
    $$PWD/randomgenerator.cpp \
	$$PWD/resource/resourceutil.cpp \
	$$PWD/resource/tanks/tankresource.cpp \
	$$PWD/resource/tanks/tankresourcelist.cpp \
	$$PWD/resource/tanks/tankresourceloader.cpp \
    $$PWD/resourcepath.cpp \
	$$PWD/server/models/mines/serverbattleminesmodel.cpp \
	$$PWD/tanks/weaponsmanager.cpp \
    $$PWD/service.cpp \
	$$PWD/tanks.cpp \
	$$PWD/alternativa/engine3d/core/object3dcontainer.cpp \
	$$PWD/flash/geom/geomrectangle.cpp \
	$$PWD/flash/geom/point.cpp \
	$$PWD/alternativa/engine3d/core/vg.cpp \
	$$PWD/alternativa/tanks/tank3d.cpp \
	$$PWD/alternativa/tanks/tank3dpart.cpp \
	$$PWD/alternativa/tanks/engine3d/animatedsprite3d.cpp \
	$$PWD/alternativa/engine3d/objects/bsp.cpp \
	$$PWD/alternativa/engine3d/containers/conflictcontainer.cpp \
	$$PWD/alternativa/engine3d/objects/sprite3d.cpp \
	$$PWD/alternativa/gfx/core/renderstate.cpp \
	$$PWD/alternativa/engine3d/core/rayintersectiondata.cpp \
	$$PWD/alternativa/tanks/models/tank/explosion/tankdeathgraphiceffect.cpp \


HEADERS += \
    $$PWD/IMain.h \
    $$PWD/alternativa/engine3d/core/Object3DFilter.h \
    $$PWD/alternativa/object/clientobjectweaponflamethrower.h \
    $$PWD/alternativa/object/clientobjectweaponfrezee.h \
    $$PWD/alternativa/object/clientobjectweaponisida.h \
    $$PWD/alternativa/object/clientobjectweaponrailgun.h \
    $$PWD/alternativa/object/clientobjectweaponricochet.h \
    $$PWD/alternativa/object/clientobjectweaponshaft.h \
    $$PWD/alternativa/object/clientobjectweaponsmoky.h \
    $$PWD/alternativa/object/clientobjectweaponterminator.h \
    $$PWD/alternativa/object/clientobjectweaponthunder.h \
    $$PWD/alternativa/object/clientobjectweapontwins.h \
    $$PWD/alternativa/tanks/model/panel/IBattleSettings.h \
    $$PWD/alternativa/tanks/models/battlefield/ambientshadows.h \
    $$PWD/alternativa/tanks/models/battlefield/gamemode/IGameMode.h \
    $$PWD/alternativa/tanks/models/battlefield/hidableobjects/HidableGraphicObject.h \
    $$PWD/alternativa/tanks/models/battlefield/hidableobjects/hidablegraphicobjects.h \
	$$PWD/alternativa/tanks/models/battlefield/logic/LogicUnit.h \
    $$PWD/alternativa/tanks/models/battlefield/logic/battlelogicunits.h \
    $$PWD/alternativa/tanks/models/battlefield/object3dnames.h \
    $$PWD/alternativa/tanks/models/battlefield/objects2tank.h \
    $$PWD/alternativa/tanks/models/effects/common/bonuscommon/ParaBonus.h \
    $$PWD/alternativa/tanks/models/effects/common/bonuscommon/cords.h \
    $$PWD/alternativa/tanks/models/sfx/healing/HealingGunSFXData.h \
    $$PWD/alternativa/tanks/models/sfx/shoot/railgun/IRailgunSFXModel.h \
    $$PWD/alternativa/tanks/models/tank/ITankEventDispatcher.h \
    $$PWD/alternativa/tanks/models/tank/ITankEventListener.h \
    $$PWD/alternativa/tanks/models/tank/TankEvent.h \
    $$PWD/alternativa/tanks/models/tank/tankeventdispatcher.h \
    $$PWD/alternativa/tanks/models/tank/turret/shaft/shaftturretcontroller.h \
    $$PWD/alternativa/tanks/models/weapon/freeze/freezedata.h \
    $$PWD/alternativa/tanks/models/weapon/freeze/freezemodel.h \
    $$PWD/alternativa/tanks/models/weapon/healing/HealingGunData.h \
    $$PWD/alternativa/tanks/models/weapon/healing/healinggunmodel.h \
    $$PWD/alternativa/tanks/models/weapon/healing/healinggunshaft.h \
    $$PWD/alternativa/tanks/models/weapon/healing/healingguntargetsystem.h \
    $$PWD/alternativa/tanks/models/weapon/railgun/RailgunData.h \
    $$PWD/alternativa/tanks/models/weapon/railgun/RailgunShotResult.h \
    $$PWD/alternativa/tanks/models/weapon/railgun/railgunmodel.h \
    $$PWD/alternativa/tanks/models/weapon/railgun/railguntargetsystem.h \
    $$PWD/alternativa/tanks/models/weapon/ricochet/IRicochetShotListener.h \
    $$PWD/alternativa/tanks/models/weapon/ricochet/RicochetData.h \
    $$PWD/alternativa/tanks/models/weapon/ricochet/ricochetmodel.h \
    $$PWD/alternativa/tanks/models/weapon/ricochet/ricochetshot.h \
    $$PWD/alternativa/tanks/models/weapon/ricochet/ricochettargetsystem.h \
    $$PWD/alternativa/tanks/models/weapon/shaft/LinearInterpolator.h \
    $$PWD/alternativa/tanks/models/weapon/shaft/ShaftData.h \
    $$PWD/alternativa/tanks/models/weapon/shaft/ShaftEnergyMode.h \
    $$PWD/alternativa/tanks/models/weapon/shaft/aim.h \
    $$PWD/alternativa/tanks/models/weapon/shaft/aimedshotresult.h \
    $$PWD/alternativa/tanks/models/weapon/shaft/cameracontrollers/targetingcameracontroller.h \
    $$PWD/alternativa/tanks/models/weapon/shaft/modes/targetingcontroller.h \
    $$PWD/alternativa/tanks/models/weapon/shaft/quickshot/shaftshotresult.h \
    $$PWD/alternativa/tanks/models/weapon/shaft/quickshot/shafttargetsystem.h \
    $$PWD/alternativa/tanks/models/weapon/shaft/setcontrollerfortemporaryitems.h \
    $$PWD/alternativa/tanks/models/weapon/shaft/shaftdeactivationtask.h \
    $$PWD/alternativa/tanks/models/weapon/shaft/shaftmodel.h \
    $$PWD/alternativa/tanks/models/weapon/shaft/states/ShaftModes.h \
    $$PWD/alternativa/tanks/models/weapon/terminator/TerminatorData.h \
    $$PWD/alternativa/tanks/models/weapon/terminator/TerminatorShotResult.h \
    $$PWD/alternativa/tanks/models/weapon/terminator/terminatormodel.h \
    $$PWD/alternativa/tanks/models/weapon/terminator/terminatortargetsystem.h \
    $$PWD/com/alternativaplatform/projects/tanks/client/warfare/models/tankparts/weapon/healing/IsisActionType.h \
    $$PWD/com/alternativaplatform/projects/tanks/client/warfare/models/tankparts/weapon/healing/struct/IsisAction.h \
    $$PWD/listvector3.h \
    $$PWD/pro/BattleDMInfoCC.h \
    $$PWD/pro/BattleInfoCC.h \
    $$PWD/pro/BattleInfoUser.h \
    $$PWD/pro/BattleItemCC.h \
    $$PWD/pro/BattleLimits.h \
    $$PWD/pro/ProBattleCC.h \
    $$PWD/pro/Range.h \
    $$PWD/pro/RotateTurretCommand.h \
    $$PWD/pro/TeamBattleInfoCC.h \
	$$PWD/pro/TeamBattleItemCC.h \
    $$PWD/_global.h \
    $$PWD/alternativa/engine3d/core/Sorting.h \
    $$PWD/alternativa/engine3d/core/camera3d.h \
    $$PWD/alternativa/engine3d/core/face.h \
    $$PWD/alternativa/engine3d/core/object3d.h \
    $$PWD/alternativa/engine3d/core/object3d_clone.h \
    $$PWD/alternativa/engine3d/core/vertex.h \
    $$PWD/alternativa/engine3d/core/view.h \
    $$PWD/alternativa/engine3d/core/wrapper.h \
    $$PWD/alternativa/engine3d/loaders/parser3ds.h \
    $$PWD/alternativa/engine3d/materials/fillmaterial.h \
    $$PWD/alternativa/engine3d/materials/material.h \
    $$PWD/alternativa/engine3d/materials/texturematerial.h \
    $$PWD/alternativa/engine3d/objects/bsp.h \
    $$PWD/alternativa/engine3d/objects/mesh.h \
    $$PWD/alternativa/gfx/core/resource.h \
    $$PWD/alternativa/gfx/core/vertexbufferresource.h \
    $$PWD/alternativa/init/battlefieldsharedactivator.h \
    $$PWD/alternativa/init/garagemodelactivator.h \
    $$PWD/alternativa/init/osgi.h \
    $$PWD/alternativa/math/matrix3.h \
    $$PWD/alternativa/math/matrix4.h \
    $$PWD/alternativa/math/quaternion.h \
    $$PWD/alternativa/math/vector3.h \
    $$PWD/alternativa/object/clientobject.h \
    $$PWD/alternativa/object/clientobjectbonus.h \
    $$PWD/alternativa/object/clientobjectctf.h \
    $$PWD/alternativa/object/clientobjecthull.h \
    $$PWD/alternativa/object/clientobjectuser.h \
    $$PWD/alternativa/object/clientobjectweapon.h \
    $$PWD/alternativa/physics/body.h \
    $$PWD/alternativa/physics/bodylist.h \
    $$PWD/alternativa/physics/bodylistitem.h \
    $$PWD/alternativa/physics/bodymaterial.h \
    $$PWD/alternativa/physics/bodystate.h \
    $$PWD/alternativa/physics/collision/IBodyCollisionPredicate.h \
    $$PWD/alternativa/physics/collision/ICollider.h \
    $$PWD/alternativa/physics/collision/ICollisionDetector.h \
    $$PWD/alternativa/physics/collision/ICollisionPredicate.h \
    $$PWD/alternativa/physics/collision/IRayCollisionPredicate.h \
    $$PWD/alternativa/physics/collision/MinMax.h \
    $$PWD/alternativa/physics/collision/colliders/boxboxcollider.h \
    $$PWD/alternativa/physics/collision/colliders/boxcollider.h \
    $$PWD/alternativa/physics/collision/colliders/boxrectcollider.h \
    $$PWD/alternativa/physics/collision/colliders/boxspherecollider.h \
    $$PWD/alternativa/physics/collision/colliders/boxtrianglecollider.h \
    $$PWD/alternativa/physics/collision/collisionkdnode.h \
    $$PWD/alternativa/physics/collision/collisionkdtree.h \
    $$PWD/alternativa/physics/collision/collisionkdtree2d.h \
	$$PWD/alternativa/physics/collision/collisionprimitive.h \
    $$PWD/alternativa/physics/collision/colliders/spherespherecollider.h \
    $$PWD/alternativa/physics/collision/kdtreecollisiondetector.h \
    $$PWD/alternativa/physics/collision/primitives/collisionbox.h \
    $$PWD/alternativa/physics/collision/primitives/collisionrect.h \
    $$PWD/alternativa/physics/collision/primitives/collisionsphere.h \
    $$PWD/alternativa/physics/collision/primitives/collisiontriangle.h \
    $$PWD/alternativa/physics/collision/types/boundbox.h \
    $$PWD/alternativa/physics/collision/types/rayintersection.h \
    $$PWD/alternativa/physics/collisionprimitivelist.h \
    $$PWD/alternativa/physics/collisionprimitivelistitem.h \
    $$PWD/alternativa/physics/constraints/constraint.h \
    $$PWD/alternativa/physics/constraints/maxdistanceconstraint.h \
    $$PWD/alternativa/physics/contact.h \
    $$PWD/alternativa/physics/contactpoint.h \
    $$PWD/alternativa/physics/physicsscene.h \
    $$PWD/alternativa/physics/physicsutils.h \
    $$PWD/alternativa/physics/rigid/body3d.h \
    $$PWD/alternativa/physics/rigid/skinnedbody3d.h \
    $$PWD/alternativa/resource/ResourceType.h \
    $$PWD/alternativa/tanks/battle/DeferredAction.h \
    $$PWD/alternativa/tanks/battle/Trigger.h \
    $$PWD/alternativa/tanks/battle/triggers/deferredtriggeraddition.h \
    $$PWD/alternativa/tanks/battle/triggers/deferredtriggerdeletion.h \
    $$PWD/alternativa/tanks/battle/triggers/triggers.h \
    $$PWD/alternativa/tanks/bonuses/BonusState.h \
    $$PWD/alternativa/tanks/bonuses/IBonus.h \
    $$PWD/alternativa/tanks/bonuses/IBonusListener.h \
    $$PWD/alternativa/tanks/camera/CameraPositionData.h \
    $$PWD/alternativa/tanks/camera/ICameraController.h \
    $$PWD/alternativa/tanks/camera/IFollowCameraController.h \
    $$PWD/alternativa/tanks/camera/anglevalues.h \
    $$PWD/alternativa/tanks/camera/cameracontrollerbase.h \
    $$PWD/alternativa/tanks/camera/camerafovcalculator.h \
    $$PWD/alternativa/tanks/camera/flycameracontroller.h \
    $$PWD/alternativa/tanks/camera/followcameracontroller.h \
    $$PWD/alternativa/tanks/camera/gamecamera.h \
    $$PWD/alternativa/tanks/config/config.h \
    $$PWD/alternativa/tanks/config/configxmlloader.h \
    $$PWD/alternativa/tanks/config/loaders/maploader.h \
    $$PWD/alternativa/tanks/config/resourceloader.h \
    $$PWD/alternativa/tanks/config/tanksmap.h \
    $$PWD/alternativa/tanks/gui/garagewindow.h \
    $$PWD/alternativa/tanks/gui/newyear/toylight.h \
    $$PWD/alternativa/tanks/model/battleselectmodel.h \
    $$PWD/alternativa/tanks/model/garagemodel.h \
    $$PWD/alternativa/tanks/model/itemparams.h \
    $$PWD/alternativa/tanks/model/panel/panelmodel.h \
    $$PWD/alternativa/tanks/model/tankpreview.h \
    $$PWD/alternativa/tanks/model/usermodel.h \
    $$PWD/alternativa/tanks/models/battlefield/IBattleField.h \
    $$PWD/alternativa/tanks/models/battlefield/IBattlefieldPlugin.h \
	$$PWD/alternativa/tanks/models/battlefield/battlefielddata.h \
	$$PWD/alternativa/tanks/models/battlefield/battlefieldmodel.h \
    $$PWD/alternativa/tanks/models/battlefield/battleview3d.h \
    $$PWD/alternativa/tanks/models/battlefield/logic/updaters/HullTransformUpdater.h \
    $$PWD/alternativa/tanks/models/battlefield/logic/updaters/localhulltransformupdater.h \
    $$PWD/alternativa/tanks/models/battlefield/logic/updaters/remotehulltransformupdater.h \
    $$PWD/alternativa/tanks/models/battlefield/mine/MineModelData.h \
    $$PWD/alternativa/tanks/models/battlefield/mine/battleminesmodel.h \
    $$PWD/alternativa/tanks/models/battlefield/mine/proximitymine.h \
    $$PWD/alternativa/tanks/models/battlefield/mine/usermineslist.h \
    $$PWD/alternativa/tanks/models/battlefield/scene3dcontainer/Scene3DContainer.h \
    $$PWD/alternativa/tanks/models/battlefield/scene3dcontainer/object3dcontainerproxy.h \
    $$PWD/alternativa/tanks/models/ctf/ClientFlag.h \
    $$PWD/alternativa/tanks/models/ctf/FlagsState.h \
    $$PWD/alternativa/tanks/models/ctf/ICTFModel.h \
    $$PWD/alternativa/tanks/models/ctf/ctfflag.h \
    $$PWD/alternativa/tanks/models/ctf/ctfflagstate.h \
    $$PWD/alternativa/tanks/models/ctf/ctfmodel.h \
    $$PWD/alternativa/tanks/models/ctf/flagdata.h \
    $$PWD/alternativa/tanks/models/ctf/initparams.h \
    $$PWD/alternativa/tanks/models/dom/cp/controlpointmarkers.h \
    $$PWD/alternativa/tanks/models/dom/dommodel.h \
    $$PWD/alternativa/tanks/models/dom/dompoint.h \
    $$PWD/alternativa/tanks/models/dom/dompointid.h \
    $$PWD/alternativa/tanks/models/dom/server/DOMPointData.h \
    $$PWD/alternativa/tanks/models/effects/common/bonuscommon/BonusCommonData.h \
    $$PWD/alternativa/tanks/models/effects/common/bonuscommon/battlebonusstate.h \
    $$PWD/alternativa/tanks/models/effects/common/bonuscommon/bonuscommonmodel.h \
    $$PWD/alternativa/tanks/models/effects/common/bonuscommon/bonusconst.h \
    $$PWD/alternativa/tanks/models/effectsvisualization/IEffectsVisualizationModel.h \
    $$PWD/alternativa/tanks/models/sfx/shoot/ICommonShootSFX.h \
    $$PWD/alternativa/tanks/models/sfx/spriteshoteffect.h \
    $$PWD/alternativa/tanks/models/tank/ITank.h \
    $$PWD/alternativa/tanks/models/tank/tankdata.h \
    $$PWD/alternativa/tanks/models/tank/tankmodel.h \
    $$PWD/alternativa/tanks/models/tank/turret/TurretController.h \
    $$PWD/alternativa/tanks/models/tank/turret/default/defaultturretcontroller.h \
    $$PWD/alternativa/tanks/models/weapon/AllGlobalGunParams.h \
    $$PWD/alternativa/tanks/models/weapon/IWeapon.h \
    $$PWD/alternativa/tanks/models/weapon/IWeaponController.h \
    $$PWD/alternativa/tanks/models/weapon/WeaponConst.h \
    $$PWD/alternativa/tanks/models/weapon/common/HitInfo.h \
    $$PWD/alternativa/tanks/models/weapon/common/IWeaponCommonModel.h \
    $$PWD/alternativa/tanks/models/weapon/common/weaponcommondata.h \
    $$PWD/alternativa/tanks/models/weapon/common/weaponcommonmodel.h \
    $$PWD/alternativa/tanks/models/weapon/flamethrower/FlamethrowerData.h \
	$$PWD/alternativa/tanks/models/weapon/flamethrower/flamethrowermodel.h \
    $$PWD/alternativa/tanks/models/weapon/flamethrower/flamethrowertargetvalidator.h \
    $$PWD/alternativa/tanks/models/weapon/gun/smokymodel.h \
    $$PWD/alternativa/tanks/models/weapon/plasma/IPlasmaShotListener.h \
    $$PWD/alternativa/tanks/models/weapon/plasma/PlasmaGunData.h \
    $$PWD/alternativa/tanks/models/weapon/plasma/plasmamodel.h \
    $$PWD/alternativa/tanks/models/weapon/plasma/plasmashot.h \
    $$PWD/alternativa/tanks/models/weapon/shared/ICommonTargetEvaluator.h \
    $$PWD/alternativa/tanks/models/weapon/shared/ITargetValidator.h \
    $$PWD/alternativa/tanks/models/weapon/shared/commontargetevaluator.h \
    $$PWD/alternativa/tanks/models/weapon/shared/commontargetsystem.h \
    $$PWD/alternativa/tanks/models/weapon/shared/commontargetsystembot.h \
    $$PWD/alternativa/tanks/models/weapon/shared/conicareatargetsystem.h \
    $$PWD/alternativa/tanks/models/weapon/shared/conicareatargetsystembot.h \
    $$PWD/alternativa/tanks/models/weapon/shared/shot/shotdata.h \
    $$PWD/alternativa/tanks/models/weapon/thunder/thunderdata.h \
    $$PWD/alternativa/tanks/models/weapon/thunder/thundermodel.h \
    $$PWD/alternativa/tanks/models/weapon/weakening/IWeaponWeakeningModel.h \
    $$PWD/alternativa/tanks/models/weapon/weakening/WeaponWeakeningData.h \
    $$PWD/alternativa/tanks/models/weapon/weakening/weaponweakeningmodel.h \
    $$PWD/alternativa/tanks/models/weapon/weaponmodelempty.h \
    $$PWD/alternativa/tanks/models/weapon/weaponutils.h \
    $$PWD/alternativa/tanks/physics/collisiongroup.h \
    $$PWD/alternativa/tanks/physics/tankscollisiondetector.h \
    $$PWD/alternativa/tanks/services/objectpool/objectpoolservice.h \
    $$PWD/alternativa/tanks/sfx/IGraphicEffect.h \
    $$PWD/alternativa/tanks/sfx/ISpecialEffect.h \
    $$PWD/alternativa/tanks/sfx/effectspair.h \
    $$PWD/alternativa/tanks/utils/mathutils.h \
    $$PWD/alternativa/tanks/utils/objectpool/objectpool.h \
    $$PWD/alternativa/tanks/utils/objectpool/pooledobject.h \
    $$PWD/alternativa/tanks/vehicles/tanks/IValueSmoother.h \
    $$PWD/alternativa/tanks/vehicles/tanks/SuspensionData.h \
    $$PWD/alternativa/tanks/vehicles/tanks/raypredicate.h \
    $$PWD/alternativa/tanks/vehicles/tanks/suspensionray.h \
    $$PWD/alternativa/tanks/vehicles/tanks/tank.h \
    $$PWD/alternativa/tanks/vehicles/tanks/tankskin.h \
    $$PWD/alternativa/tanks/vehicles/tanks/tankskinhull.h \
    $$PWD/alternativa/tanks/vehicles/tanks/tankskinpart.h \
    $$PWD/alternativa/tanks/vehicles/tanks/tankskinturret.h \
    $$PWD/alternativa/tanks/vehicles/tanks/track.h \
    $$PWD/alternativa/tanks/vehicles/tanks/valuesmoother.h \
    $$PWD/alternativa/types/long.h \
    $$PWD/alternativa/utils/ITextureConstructorListener.h \
	$$PWD/com/alternativaplatform/projects/tanks/client/commons/types/deathreason.h \
	$$PWD/com/alternativaplatform/projects/tanks/client/models/battlefield/mine/battlemine.h \
	$$PWD/com/alternativaplatform/projects/tanks/client/models/tank/ClientTank.h \
	$$PWD/com/alternativaplatform/projects/tanks/client/models/tank/TankSpawnState.h \
	$$PWD/com/alternativaplatform/projects/tanks/client/commons/types/TankSpecification.h \
	$$PWD/com/alternativaplatform/projects/tanks/client/commons/types/TankState.h \
	$$PWD/com/alternativaplatform/projects/tanks/client/commons/types/tankparts.h \
    $$PWD/battlechatmessage.h \
    $$PWD/battlecontroller.h \
    $$PWD/com/alternativaplatform/projects/tanks/client/commons/models/itemtype/itemtypeenum.h \
    $$PWD/com/alternativaplatform/projects/tanks/client/commons/models/itemtype/itemtypeenumfromint.h \
    $$PWD/com/alternativaplatform/projects/tanks/client/commons/types/ItemProperty.h \
    $$PWD/com/alternativaplatform/projects/tanks/client/commons/types/itempropertyfromstring.h \
    $$PWD/com/alternativaplatform/projects/tanks/client/garage/garage/iteminfo.h \
    $$PWD/com/alternativaplatform/projects/tanks/client/garage/item/itempropertyvalue.h \
    $$PWD/com/alternativaplatform/projects/tanks/client/garage/item/modificationinfo.h \
    $$PWD/double_to_string.h \
    $$PWD/enterbattle.h \
    $$PWD/file.h \
    $$PWD/flash/display/BlendMode.h \
    $$PWD/flash/geom/colortransform.h \
    $$PWD/flash/geom/matrix.h \
    $$PWD/flash/geom/matrix3d.h \
    $$PWD/flash/utils/gettimer.h \
    $$PWD/forms/events/MainButtonBarEvents.h \
    $$PWD/forms/garage/partslist.h \
    $$PWD/gametime.h \
    $$PWD/get_dir.h \
    $$PWD/hash.h \
    $$PWD/keys.h \
    $$PWD/lobby.h \
    $$PWD/mymath.h \
    $$PWD/pro/BattleDMItemCC.h \
    $$PWD/pro/battlemode.h \
    $$PWD/projects/tanks/client/battleselect/types/BattleClient.h \
    $$PWD/projects/tanks/client/battleselect/types/mapclient.h \
    $$PWD/projects/tanks/client/battleselect/types/showbattleinfo.h \
    $$PWD/projects/tanks/client/battleservice/model/battletype.h \
    $$PWD/projects/tanks/client/battleservice/model/team/BattleTeamType.h \
    $$PWD/projects/tanks/client/battleservice/model/team/UserInfoClient.h \
    $$PWD/qhash_ptr.h \
	$$PWD/networking/INetworkListener.h \
	$$PWD/networking/INetworker.h \
	$$PWD/networking/commands/CommandType.h \
	$$PWD/networking/commands/command.h \
	$$PWD/networking/network.h \
	$$PWD/networking/networkbytes.h \
	$$PWD/networking/networkservice.h \
    $$PWD/randomgenerator.h \
	$$PWD/resource/ResourceType.h \
	$$PWD/resource/resourceutil.h \
	$$PWD/resource/tanks/tankresource.h \
	$$PWD/resource/tanks/tankresourcelist.h \
	$$PWD/resource/tanks/tankresourceloader.h \
    $$PWD/resourcepath.h \
	$$PWD/server/models/mines/serverbattleminesmodel.h \
    $$PWD/server/models/shaft/ServerShaftTargetData.h \
	$$PWD/tanks/weaponsmanager.h \
    $$PWD/service.h \
    $$PWD/settings.h \
	$$PWD/tanks.h \
	$$PWD/alternativa/engine3d/core/object3dcontainer.h \
	$$PWD/flash/geom/geomrectangle.h \
	$$PWD/flash/geom/point.h \
	$$PWD/alternativa/gfx/core/indexbufferresource.h \
	$$PWD/alternativa/engine3d/core/vg.h \
	$$PWD/alternativa/tanks/tank3d.h \
	$$PWD/alternativa/tanks/tank3dpart.h \
	$$PWD/alternativa/tanks/engine3d/animatedsprite3d.h \
	$$PWD/alternativa/engine3d/containers/conflictcontainer.h \
	$$PWD/alternativa/engine3d/objects/sprite3d.h \
	$$PWD/alternativa/gfx/core/renderstate.h \
	$$PWD/utils/double_array.h \
	$$PWD/alternativa/engine3d/core/rayintersectiondata.h \
	$$PWD/alternativa/tanks/models/tank/explosion/tankdeathgraphiceffect.h \


CONFIG_GT {
    SOURCES += \
	    $$PWD/botmodel.cpp \

    HEADERS += \
	    $$PWD/botmodel.h \
}

TANK_BOT {
    SOURCES += \
	    $$PWD/tank_bot/bot_points.cpp \
		$$PWD/tank_bot/astar.cpp \
		$$PWD/tank_bot/bot.cpp \
		$$PWD/tank_bot/bot_flamethrower.cpp \
		$$PWD/tank_bot/bot_shot.cpp \
		$$PWD/tank_bot/bot_smoky.cpp \
		$$PWD/tank_bot/bot_utils.cpp \
		$$PWD/tank_bot/botsettings.cpp \
		$$PWD/tank_bot/map_list_path.cpp \
		$$PWD/tank_bot/map_points.cpp \
		$$PWD/tank_bot/map_points_file.cpp \
		$$PWD/tank_bot/path_normalize.cpp \
		$$PWD/tank_bot/tank_control.cpp \

    HEADERS += \
	    $$PWD/tank_bot/bot_points.h \
		$$PWD/tank_bot/astar.h \
		$$PWD/tank_bot/bot.h \
		$$PWD/tank_bot/bot_flamethrower.h \
		$$PWD/tank_bot/bot_shot.h \
		$$PWD/tank_bot/bot_smoky.h \
		$$PWD/tank_bot/bot_utils.h \
		$$PWD/tank_bot/botsettings.h \
		$$PWD/tank_bot/map_list_path.h \
		$$PWD/tank_bot/map_points.h \
		$$PWD/tank_bot/map_points_file.h \
		$$PWD/tank_bot/path_normalize.h \
		$$PWD/tank_bot/tank_control.h \
}

CONFIG(CLASS_NORMAL, CLASS_NORMAL|CLASS_LIGHTWEIGHT) {
    SOURCES += \
	    $$PWD/alternativa/engine3d/core/camera3d.cpp \
		$$PWD/alternativa/engine3d/core/object3d_clone.cpp \
		$$PWD/alternativa/engine3d/materials/texturematerial.cpp \
		$$PWD/alternativa/gfx/core/vertexbufferresource.cpp \
		$$PWD/alternativa/gfx/core/indexbufferresource.cpp \


} else {
    SOURCES += \
	    $$PWD/alternativa/engine3d/core/lightweight_camera3d.cpp \
		$$PWD/alternativa/engine3d/core/lightweight_object3d_clone.cpp \
		$$PWD/alternativa/gfx/core/lightweight_device.cpp \
		$$PWD/alternativa/gfx/core/lightweight_indexbufferresource.cpp \
		$$PWD/alternativa/gfx/core/lightweight_vertexbufferresource.cpp \
                $$PWD/alternativa/engine3d/materials/lightweight_texturematerial.cpp \
}

__BONUS_TYPE_1 {
    SOURCES += \
	    $$PWD/alternativa/tanks/models/effects/common/bonuscommon/parabonus1.cpp \
		$$PWD/alternativa/tanks/models/effects/common/bonuscommon/cords1.cpp \
    $$PWD/alternativa/tanks/models/effects/common/bonuscommon/parachute1.cpp

    HEADERS += \
	    $$PWD/alternativa/tanks/models/effects/common/bonuscommon/parabonus1.h \
		$$PWD/alternativa/tanks/models/effects/common/bonuscommon/cords1.h \
    $$PWD/alternativa/tanks/models/effects/common/bonuscommon/parachute1.h \
}

__BONUS_TYPE_2 {
    SOURCES += \
	    $$PWD/alternativa/tanks/models/effects/common/bonuscommon/fallcontroller.cpp \
		$$PWD/alternativa/tanks/models/effects/common/bonuscommon/landingcontroller.cpp \
		$$PWD/alternativa/tanks/models/effects/common/bonuscommon/parabonus2.cpp \
		$$PWD/alternativa/tanks/models/effects/common/bonuscommon/bonustrigger.cpp \
		$$PWD/alternativa/tanks/models/effects/common/bonuscommon/cords2.cpp \
		$$PWD/alternativa/tanks/models/effects/common/bonuscommon/landingstate.cpp \
		$$PWD/alternativa/tanks/models/effects/common/bonuscommon/objectcache.cpp \
		$$PWD/alternativa/tanks/models/effects/common/bonuscommon/parachute2.cpp \
		$$PWD/alternativa/tanks/models/effects/common/bonuscommon/bonuscache.cpp \
		$$PWD/alternativa/tanks/models/effects/common/bonuscommon/bonusmesh.cpp \

    HEADERS += \
	    $$PWD/alternativa/tanks/models/effects/common/bonuscommon/fallcontroller.h \
		$$PWD/alternativa/tanks/models/effects/common/bonuscommon/landingcontroller.h \
		$$PWD/alternativa/tanks/models/effects/common/bonuscommon/parabonus2.h \
		$$PWD/alternativa/tanks/models/effects/common/bonuscommon/bonustrigger.h \
		$$PWD/alternativa/tanks/models/effects/common/bonuscommon/cords2.h \
		$$PWD/alternativa/tanks/models/effects/common/bonuscommon/landingstate.h \
		$$PWD/alternativa/tanks/models/effects/common/bonuscommon/objectcache.h \
		$$PWD/alternativa/tanks/models/effects/common/bonuscommon/parachute2.h \
		$$PWD/alternativa/tanks/models/effects/common/bonuscommon/bonuscache.h \
		$$PWD/alternativa/tanks/models/effects/common/bonuscommon/bonusmesh.h \
}

