#ifndef ITEMPROPERTY_H
#define ITEMPROPERTY_H

enum class ItemProperty
{
	DAMAGE,
	DAMAGE_PER_SECOND,
	AIMING_ERROR,
	CONE_ANGLE,
	SHOT_AREA,
	SHOT_FREQUENCY,
	SHOT_RANGE,
	TURN_SPEED,
	MECH_RESISTANCE,
	PLASMA_RESISTANCE,
	RAIL_RESISTANCE,
	TERMINATOR_RESISTANCE,
	MINE_RESISTANCE,
	CRITICAL_CHANCE,
	HEATING_TIME,
	VAMPIRE_RESISTANCE,
	ARMOR,
	TURRET_TURN_SPEED,
	FIRE_RESISTANCE,
	THUNDER_RESISTANCE,
	FREEZE_RESISTANCE,
	RICOCHET_RESISTANCE,
	HEALING_RADUIS,
	HEAL_RATE,
	VAMPIRE_RATE,
	SPEED,
	SHAFT_DAMAGE,
	SHAFT_FIRE_RATE,
	SHAFT_RESISTANCE,
};


#endif // ITEMPROPERTY_H
