#ifndef DEPTHRENDERERLIGHTFRAGMENTSHADERHLSL_H
#define DEPTHRENDERERLIGHTFRAGMENTSHADERHLSL_H

class QByteArray;

QByteArray DepthRendererLightFragmentShaderHLSL(int param1);

#endif // DEPTHRENDERERLIGHTFRAGMENTSHADERHLSL_H
