#ifndef DEPTHRENDERERLIGHTVERTEXSHADERHLSL_H
#define DEPTHRENDERERLIGHTVERTEXSHADERHLSL_H

class QByteArray;

QByteArray DepthRendererLightVertexShaderHLSL(int n);

#endif // DEPTHRENDERERLIGHTVERTEXSHADERHLSL_H
