#ifndef DEPTHRENDERERBLURVERTEXSHADERHLSL_H
#define DEPTHRENDERERBLURVERTEXSHADERHLSL_H

class QByteArray;

QByteArray DepthRendererBlurVertexShaderHLSL();

#endif // DEPTHRENDERERBLURVERTEXSHADERHLSL_H
