#ifndef DEPTHRENDERERSSAOVERTEXSHADERHLSL_H
#define DEPTHRENDERERSSAOVERTEXSHADERHLSL_H

class QByteArray;

QByteArray DepthRendererSSAOVertexShaderHLSL();

#endif // DEPTHRENDERERSSAOVERTEXSHADERHLSL_H
