#ifndef DEPTHRENDERERDEPTHVERTEXSHADERHLSL_H
#define DEPTHRENDERERDEPTHVERTEXSHADERHLSL_H

class QByteArray;

QByteArray DepthRendererDepthVertexShaderHLSL(bool param1, bool param2);

#endif // DEPTHRENDERERDEPTHVERTEXSHADERHLSL_H
