#ifndef SHADOWRECEIVERVERTEXSHADERHLSL_H
#define SHADOWRECEIVERVERTEXSHADERHLSL_H

class QByteArray;

QByteArray ShadowReceiverVertexShaderHLSL(bool param1);

#endif // SHADOWRECEIVERVERTEXSHADERHLSL_H
